import 'package:flutter/material.dart';
import 'package:flutterapp/telmexapp/generatedasistente1widget/generated/GeneratedLine21Widget.dart';
import 'package:flutterapp/telmexapp/generatedasistente1widget/generated/GeneratedBARRAWidget5.dart';
import 'package:flutterapp/telmexapp/generatedasistente1widget/generated/GeneratedLine19Widget.dart';
import 'package:flutterapp/telmexapp/generatedasistente1widget/generated/GeneratedLine22Widget.dart';
import 'package:flutterapp/telmexapp/generatedasistente1widget/generated/GeneratedRectangle11Widget.dart';
import 'package:flutterapp/telmexapp/generatedasistente1widget/generated/GeneratedLine24Widget.dart';
import 'package:flutterapp/telmexapp/generatedasistente1widget/generated/GeneratedHolaNavaEnquetepuedoayudarWidget.dart';
import 'package:flutterapp/telmexapp/generatedasistente1widget/generated/GeneratedLine25Widget.dart';
import 'package:flutterapp/telmexapp/generatedasistente1widget/generated/GeneratedLine23Widget.dart';
import 'package:flutterapp/telmexapp/generatedasistente1widget/generated/GeneratedPeoplesharpWidget3.dart';
import 'package:flutterapp/telmexapp/generatedasistente1widget/generated/GeneratedAsistenciaenLineaWidget.dart';
import 'package:flutterapp/telmexapp/generatedasistente1widget/generated/GeneratedMeinteresaDisneyenInfinitumDudasobremireciboRepararmise.dart';
import 'package:flutterapp/telmexapp/generatedasistente1widget/generated/GeneratedLine20Widget.dart';
import 'package:flutterapp/telmexapp/generatedasistente1widget/generated/GeneratedRectangle12Widget.dart';
import 'package:flutterapp/telmexapp/generatedasistente1widget/generated/GeneratedRectangle13Widget.dart';

/* Frame Asistente1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAsistente1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 245, 245),
                ),
              ),
              Positioned(
                left: 169.0,
                top: 791.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 75.0,
                child: GeneratedBARRAWidget5(),
              ),
              Positioned(
                left: 1.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 81.0,
                child: GeneratedRectangle11Widget(),
              ),
              Positioned(
                left: 99.0,
                top: 34.0,
                right: null,
                bottom: null,
                width: 283.0,
                height: 41.0,
                child: GeneratedAsistenciaenLineaWidget(),
              ),
              Positioned(
                left: 38.0,
                top: 26.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 50.0,
                child: GeneratedPeoplesharpWidget3(),
              ),
              Positioned(
                left: 10.0,
                top: 103.0,
                right: null,
                bottom: null,
                width: 393.0,
                height: 44.0,
                child: GeneratedRectangle12Widget(),
              ),
              Positioned(
                left: 19.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 435.0,
                child: GeneratedRectangle13Widget(),
              ),
              Positioned(
                left: 1.0,
                top: 111.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 38.0,
                child: GeneratedHolaNavaEnquetepuedoayudarWidget(),
              ),
              Positioned(
                left: 36.0,
                top: 170.0,
                right: null,
                bottom: null,
                width: 363.0,
                height: 414.0,
                child:
                    GeneratedMeinteresaDisneyenInfinitumDudasobremireciboRepararmise(),
              ),
              Positioned(
                left: 30.0,
                top: 229.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 1.0,
                child: GeneratedLine19Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 288.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 1.0,
                child: GeneratedLine20Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 338.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 1.0,
                child: GeneratedLine21Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 392.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 1.0,
                child: GeneratedLine22Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 444.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 1.0,
                child: GeneratedLine23Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 498.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 1.0,
                child: GeneratedLine24Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 549.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 1.0,
                child: GeneratedLine25Widget(),
              )
            ]),
      ),
    ));
  }
}
