import 'package:flutter/material.dart';
import 'package:flutterapp/telmexapp/generatedayudaconredwidget/generated/GeneratedLine31Widget.dart';
import 'package:flutterapp/telmexapp/generatedayudaconredwidget/generated/GeneratedLine32Widget.dart';
import 'package:flutterapp/telmexapp/generatedayudaconredwidget/generated/GeneratedLine30Widget.dart';
import 'package:flutterapp/telmexapp/generatedayudaconredwidget/generated/GeneratedBARRAWidget4.dart';
import 'package:flutterapp/telmexapp/generatedayudaconredwidget/generated/GeneratedSigueestosconsejossobreelcorrectousodelmdemparamejorary.dart';
import 'package:flutterapp/telmexapp/generatedayudaconredwidget/generated/GeneratedLine29Widget.dart';

/* Frame Ayuda con Red
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAyudaconRedWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 245, 245),
                ),
              ),
              Positioned(
                left: 169.0,
                top: 791.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 75.0,
                child: GeneratedBARRAWidget4(),
              ),
              Positioned(
                left: 17.0,
                top: 41.0,
                right: null,
                bottom: null,
                width: 399.0,
                height: 741.0,
                child:
                    GeneratedSigueestosconsejossobreelcorrectousodelmdemparamejorary(),
              ),
              Positioned(
                left: 24.0,
                top: 280.0,
                right: null,
                bottom: null,
                width: 366.0,
                height: 1.0,
                child: GeneratedLine30Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 393.0,
                right: null,
                bottom: null,
                width: 366.0,
                height: 1.0,
                child: GeneratedLine29Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 509.0,
                right: null,
                bottom: null,
                width: 366.0,
                height: 1.0,
                child: GeneratedLine31Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 604.0,
                right: null,
                bottom: null,
                width: 366.0,
                height: 1.0,
                child: GeneratedLine32Widget(),
              )
            ]),
      ),
    ));
  }
}
