import 'package:flutter/material.dart';
import 'package:flutterapp/telmexapp/generatediniciowidget/generated/GeneratedBIENVENIDONavaWidget.dart';
import 'package:flutterapp/telmexapp/generatediniciowidget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/telmexapp/generatediniciowidget/generated/GeneratedPagarantesdel140521Widget.dart';
import 'package:flutterapp/telmexapp/generatediniciowidget/generated/GeneratedBARRAWidget.dart';
import 'package:flutterapp/telmexapp/generatediniciowidget/generated/GeneratedRectangle17Widget.dart';
import 'package:flutterapp/telmexapp/generatediniciowidget/generated/GeneratedRectangle57Widget.dart';
import 'package:flutterapp/telmexapp/generatediniciowidget/generated/GeneratedLine33Widget.dart';
import 'package:flutterapp/telmexapp/generatediniciowidget/generated/GeneratedRectangle37Widget.dart';
import 'package:flutterapp/telmexapp/generatediniciowidget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/telmexapp/generatediniciowidget/generated/GeneratedAsistenciaWidget.dart';
import 'package:flutterapp/telmexapp/generatediniciowidget/generated/Generated\$999Widget.dart';
import 'package:flutterapp/telmexapp/generatediniciowidget/generated/GeneratedFacturaWidget.dart';
import 'package:flutterapp/telmexapp/generatediniciowidget/generated/GeneratedWiFiWidget.dart';
import 'package:flutterapp/telmexapp/generatediniciowidget/generated/GeneratedLine34Widget.dart';
import 'package:flutterapp/telmexapp/generatediniciowidget/generated/GeneratedCompartirRedWidget.dart';
import 'package:flutterapp/telmexapp/generatediniciowidget/generated/GeneratedRectangle20Widget.dart';

/* Frame INICIO
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedINICIOWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 245, 245),
                ),
              ),
              Positioned(
                left: -10.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 424.0,
                height: 213.0,
                child: GeneratedRectangle5Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 62.0,
                right: null,
                bottom: null,
                width: 354.0,
                height: 302.0,
                child: GeneratedRectangle6Widget(),
              ),
              Positioned(
                left: 164.0,
                top: 805.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 75.0,
                child: GeneratedBARRAWidget(),
              ),
              Positioned(
                left: 10.0,
                top: 405.0,
                right: null,
                bottom: null,
                width: 384.0,
                height: 1.0,
                child: GeneratedLine33Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 467.0,
                right: null,
                bottom: null,
                width: 384.0,
                height: 1.0,
                child: GeneratedLine34Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 508.0,
                right: null,
                bottom: null,
                width: 164.0,
                height: 93.0,
                child: GeneratedRectangle17Widget(),
              ),
              Positioned(
                left: 59.0,
                top: 540.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 35.0,
                child: GeneratedFacturaWidget(),
              ),
              Positioned(
                left: 18.0,
                top: 656.0,
                right: null,
                bottom: null,
                width: 164.0,
                height: 93.0,
                child: GeneratedRectangle20Widget(),
              ),
              Positioned(
                left: 217.0,
                top: 656.0,
                right: null,
                bottom: null,
                width: 164.0,
                height: 93.0,
                child: GeneratedRectangle57Widget(),
              ),
              Positioned(
                left: 217.0,
                top: 508.0,
                right: null,
                bottom: null,
                width: 164.0,
                height: 93.0,
                child: GeneratedRectangle37Widget(),
              ),
              Positioned(
                left: 240.0,
                top: 688.0,
                right: null,
                bottom: null,
                width: 122.0,
                height: 35.0,
                child: GeneratedAsistenciaWidget(),
              ),
              Positioned(
                left: 240.0,
                top: 525.0,
                right: null,
                bottom: null,
                width: 122.0,
                height: 62.0,
                child: GeneratedCompartirRedWidget(),
              ),
              Positioned(
                left: 67.0,
                top: 688.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 35.0,
                child: GeneratedWiFiWidget(),
              ),
              Positioned(
                left: 23.0,
                top: 421.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 29.0,
                child: GeneratedBIENVENIDONavaWidget(),
              ),
              Positioned(
                left: 50.0,
                top: 292.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 42.0,
                child: GeneratedPagarantesdel140521Widget(),
              ),
              Positioned(
                left: 91.0,
                top: 131.0,
                right: null,
                bottom: null,
                width: 226.0,
                height: 125.0,
                child: Generated$999Widget(),
              )
            ]),
      ),
    ));
  }
}
