import 'package:flutter/material.dart';
import 'package:flutterapp/telmexapp/generatedentretenimientowidget6/generated/Generated1366_20001Widget.dart';
import 'package:flutterapp/telmexapp/generatedentretenimientowidget6/generated/GeneratedBARRAWidget6.dart';
import 'package:flutterapp/telmexapp/generatedentretenimientowidget6/generated/GeneratedImages1Widget.dart';
import 'package:flutterapp/telmexapp/generatedentretenimientowidget6/generated/GeneratedDott_bg1Widget.dart';
import 'package:flutterapp/telmexapp/generatedentretenimientowidget6/generated/GeneratedSeowatchfreelinkpreview1Widget.dart';

/* Frame Entretenimiento
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEntretenimientoWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 245, 245),
                ),
              ),
              Positioned(
                left: 169.0,
                top: 791.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 75.0,
                child: GeneratedBARRAWidget6(),
              ),
              Positioned(
                left: -19.0,
                top: 659.0,
                right: null,
                bottom: null,
                width: 433.0,
                height: 132.0,
                child: GeneratedDott_bg1Widget(),
              ),
              Positioned(
                left: 3.0,
                top: 209.0,
                right: null,
                bottom: null,
                width: 413.0,
                height: 225.0,
                child: GeneratedSeowatchfreelinkpreview1Widget(),
              ),
              Positioned(
                left: 2.0,
                top: 434.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 225.0,
                child: Generated1366_20001Widget(),
              ),
              Positioned(
                left: 3.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 417.0,
                height: 216.0,
                child: GeneratedImages1Widget(),
              )
            ]),
      ),
    ));
  }
}
