import 'package:flutter/material.dart';
import 'package:flutterapp/telmexapp/generatedwificodigowidget/generated/GeneratedCompartirredWidget2.dart';
import 'package:flutterapp/telmexapp/generatedwificodigowidget/generated/GeneratedAyudaconlaredWidget1.dart';
import 'package:flutterapp/telmexapp/generatedwificodigowidget/generated/GeneratedAsistenciaWidget4.dart';
import 'package:flutterapp/telmexapp/generatedwificodigowidget/generated/GeneratedRectangle10Widget.dart';
import 'package:flutterapp/telmexapp/generatedwificodigowidget/generated/GeneratedVectorWidget82.dart';
import 'package:flutterapp/telmexapp/generatedwificodigowidget/generated/GeneratedLine14Widget2.dart';
import 'package:flutterapp/telmexapp/generatedwificodigowidget/generated/Generated15642Widget1.dart';
import 'package:flutterapp/telmexapp/generatedwificodigowidget/generated/GeneratedLogorssWidget1.dart';
import 'package:flutterapp/telmexapp/generatedwificodigowidget/generated/GeneratedCompartirmiRedWidget2.dart';
import 'package:flutterapp/telmexapp/generatedwificodigowidget/generated/GeneratedWifiWidget4.dart';
import 'package:flutterapp/telmexapp/generatedwificodigowidget/generated/GeneratedFlowcode1Widget.dart';
import 'package:flutterapp/telmexapp/generatedwificodigowidget/generated/GeneratedWidget2.dart';
import 'package:flutterapp/telmexapp/generatedwificodigowidget/generated/GeneratedCaretbacksharpWidget.dart';
import 'package:flutterapp/telmexapp/generatedwificodigowidget/generated/GeneratedEllipse2Widget1.dart';
import 'package:flutterapp/telmexapp/generatedwificodigowidget/generated/GeneratedContraseaWidget4.dart';
import 'package:flutterapp/telmexapp/generatedwificodigowidget/generated/GeneratedQrcodesharpWidget2.dart';
import 'package:flutterapp/telmexapp/generatedwificodigowidget/generated/GeneratedLine16Widget1.dart';
import 'package:flutterapp/telmexapp/generatedwificodigowidget/generated/GeneratedMiredWidget4.dart';
import 'package:flutterapp/telmexapp/generatedwificodigowidget/generated/GeneratedApagarredWidget1.dart';
import 'package:flutterapp/telmexapp/generatedwificodigowidget/generated/GeneratedRectangle8Widget1.dart';
import 'package:flutterapp/telmexapp/generatedwificodigowidget/generated/GeneratedRectangle9Widget2.dart';
import 'package:flutterapp/telmexapp/generatedwificodigowidget/generated/GeneratedMiredWidget5.dart';
import 'package:flutterapp/telmexapp/generatedwificodigowidget/generated/GeneratedConstructsharpWidget2.dart';
import 'package:flutterapp/telmexapp/generatedwificodigowidget/generated/GeneratedKeysharpWidget2.dart';
import 'package:flutterapp/telmexapp/generatedwificodigowidget/generated/GeneratedLine13Widget1.dart';
import 'package:flutterapp/telmexapp/generatedwificodigowidget/generated/GeneratedContraseaWidget5.dart';
import 'package:flutterapp/telmexapp/generatedwificodigowidget/generated/GeneratedLine17Widget2.dart';
import 'package:flutterapp/telmexapp/generatedwificodigowidget/generated/GeneratedModeloWidget3.dart';
import 'package:flutterapp/telmexapp/generatedwificodigowidget/generated/GeneratedLine15Widget2.dart';
import 'package:flutterapp/telmexapp/generatedwificodigowidget/generated/GeneratedPeoplesharpWidget1.dart';
import 'package:flutterapp/telmexapp/generatedwificodigowidget/generated/GeneratedAsistenciaWidget5.dart';
import 'package:flutterapp/telmexapp/generatedwificodigowidget/generated/GeneratedEaselWidget1.dart';
import 'package:flutterapp/telmexapp/generatedwificodigowidget/generated/GeneratedHomesharpWidget2.dart';
import 'package:flutterapp/telmexapp/generatedwificodigowidget/generated/GeneratedModeloWidget2.dart';
import 'package:flutterapp/telmexapp/generatedwificodigowidget/generated/GeneratedAyudaconmiRedWidget2.dart';
import 'package:flutterapp/telmexapp/generatedwificodigowidget/generated/GeneratedMICHISWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/telmexapp/generatedwificodigowidget/generated/GeneratedGestiondeWiFiWidget1.dart';
import 'package:flutterapp/telmexapp/generatedwificodigowidget/generated/GeneratedLine18Widget2.dart';

/* Frame WIFIcodigo
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWIFIcodigoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 245, 245),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 435.0,
                height: 203.0,
                child: GeneratedRectangle8Widget1(),
              ),
              Positioned(
                left: -15.0,
                top: -19.0,
                right: null,
                bottom: null,
                width: 456.0,
                height: 101.0,
                child: GeneratedRectangle9Widget2(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 214.0,
                height: 197.0,
                child: TransformHelper.translate(
                    x: -10.00,
                    y: -255.50,
                    z: 0,
                    child: GeneratedEllipse2Widget1()),
              ),
              Positioned(
                left: 108.0,
                top: 110.0,
                right: null,
                bottom: null,
                width: 177.0,
                height: 180.0,
                child: GeneratedWifiWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 31.0,
                right: null,
                bottom: null,
                width: 416.0,
                height: 49.0,
                child: GeneratedGestiondeWiFiWidget1(),
              ),
              Positioned(
                left: 26.0,
                top: 307.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedQrcodesharpWidget2(),
              ),
              Positioned(
                left: 87.0,
                top: 307.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 30.0,
                child: GeneratedCompartirmiRedWidget2(),
              ),
              Positioned(
                left: 90.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 30.0,
                child: GeneratedMiredWidget4(),
              ),
              Positioned(
                left: 90.0,
                top: 426.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 33.0,
                child: GeneratedContraseaWidget4(),
              ),
              Positioned(
                left: 90.0,
                top: 516.0,
                right: null,
                bottom: null,
                width: 119.0,
                height: 30.0,
                child: GeneratedApagarredWidget1(),
              ),
              Positioned(
                left: 90.0,
                top: 652.0,
                right: null,
                bottom: null,
                width: 194.0,
                height: 30.0,
                child: GeneratedAyudaconmiRedWidget2(),
              ),
              Positioned(
                left: 90.0,
                top: 729.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 33.0,
                child: GeneratedAsistenciaWidget4(),
              ),
              Positioned(
                left: 6.0,
                top: 357.0,
                right: null,
                bottom: null,
                width: 403.9989929199219,
                height: 1.0,
                child: GeneratedLine13Widget1(),
              ),
              Positioned(
                left: 6.0,
                top: 426.0,
                right: null,
                bottom: null,
                width: 403.9989929199219,
                height: 1.0,
                child: GeneratedLine14Widget2(),
              ),
              Positioned(
                left: 6.0,
                top: 495.0,
                right: null,
                bottom: null,
                width: 403.9989929199219,
                height: 1.0,
                child: GeneratedLine15Widget2(),
              ),
              Positioned(
                left: 6.0,
                top: 564.0,
                right: null,
                bottom: null,
                width: 403.9989929199219,
                height: 1.0,
                child: GeneratedLine16Widget1(),
              ),
              Positioned(
                left: 6.0,
                top: 633.0,
                right: null,
                bottom: null,
                width: 403.9989929199219,
                height: 1.0,
                child: GeneratedLine17Widget2(),
              ),
              Positioned(
                left: 6.0,
                top: 702.0,
                right: null,
                bottom: null,
                width: 403.9989929199219,
                height: 1.0,
                child: GeneratedLine18Widget2(),
              ),
              Positioned(
                left: 90.0,
                top: 567.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 30.0,
                child: GeneratedModeloWidget2(),
              ),
              Positioned(
                left: 26.0,
                top: 376.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedHomesharpWidget2(),
              ),
              Positioned(
                left: 24.0,
                top: 728.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedPeoplesharpWidget1(),
              ),
              Positioned(
                left: 28.0,
                top: 448.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedKeysharpWidget2(),
              ),
              Positioned(
                left: 28.0,
                top: 652.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedConstructsharpWidget2(),
              ),
              Positioned(
                left: 24.0,
                top: 584.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedEaselWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.10869565217391304;
                  double scaleX = (constraints.maxWidth * percentWidth) / 45.0;

                  double percentHeight = 0.027901785714285716;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 25.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8671497584541062,
                        translateY: constraints.maxHeight * 0.5792410714285714,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget82())
                  ]);
                }),
              ),
              Positioned(
                left: 364.0,
                top: 383.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedMiredWidget5(),
              ),
              Positioned(
                left: 364.0,
                top: 452.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedContraseaWidget5(),
              ),
              Positioned(
                left: 28.0,
                top: 514.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedLogorssWidget1(),
              ),
              Positioned(
                left: 366.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedCompartirredWidget2(),
              ),
              Positioned(
                left: 366.0,
                top: 584.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedModeloWidget3(),
              ),
              Positioned(
                left: 366.0,
                top: 655.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedAyudaconlaredWidget1(),
              ),
              Positioned(
                left: 366.0,
                top: 731.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedAsistenciaWidget5(),
              ),
              Positioned(
                left: 32.0,
                top: 386.0,
                right: null,
                bottom: null,
                width: 203.0,
                height: 34.0,
                child: GeneratedMICHISWidget2(),
              ),
              Positioned(
                left: 85.0,
                top: 421.0,
                right: null,
                bottom: null,
                width: 157.0,
                height: 80.0,
                child: GeneratedWidget2(),
              ),
              Positioned(
                left: 87.0,
                top: 598.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 33.0,
                child: Generated15642Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 359.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 608.0,
                child: GeneratedRectangle10Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 415.0,
                right: null,
                bottom: null,
                width: 369.0,
                height: 377.0,
                child: GeneratedFlowcode1Widget(),
              ),
              Positioned(
                left: -88.0,
                top: 602.0,
                right: null,
                bottom: null,
                width: 512.0,
                height: 512.0,
                child: GeneratedCaretbacksharpWidget(),
              )
            ]),
      ),
    ));
  }
}
