import 'package:flutter/material.dart';
import 'package:flutterapp/telmexapp/generatedformasdepagowidget/generated/GeneratedPagoseguropaypal1Widget.dart';
import 'package:flutterapp/telmexapp/generatedformasdepagowidget/generated/GeneratedFormasdePagoWidget.dart';
import 'package:flutterapp/telmexapp/generatedformasdepagowidget/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/telmexapp/generatedformasdepagowidget/generated/GeneratedBARRAWidget8.dart';
import 'package:flutterapp/telmexapp/generatedformasdepagowidget/generated/GeneratedPagartelmex825x2941Widget.dart';

/* Frame Formas de pago
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFormasdepagoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 245, 245),
                ),
              ),
              Positioned(
                left: 169.0,
                top: 791.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 75.0,
                child: GeneratedBARRAWidget8(),
              ),
              Positioned(
                left: 0.0,
                top: 477.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 226.0,
                child: GeneratedPagoseguropaypal1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 98.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 303.0,
                child: GeneratedPagartelmex825x2941Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 98.0,
                child: GeneratedRectangle14Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 36.0,
                right: null,
                bottom: null,
                width: 367.0,
                height: 64.0,
                child: GeneratedFormasdePagoWidget(),
              )
            ]),
      ),
    ));
  }
}
