import 'package:flutter/material.dart';
import 'package:flutterapp/telmexapp/generatedmipaqwidget/generated/GeneratedRecargasWidget.dart';
import 'package:flutterapp/telmexapp/generatedmipaqwidget/generated/GeneratedLine16Widget3.dart';
import 'package:flutterapp/telmexapp/generatedmipaqwidget/generated/GeneratedHistorialWidget.dart';
import 'package:flutterapp/telmexapp/generatedmipaqwidget/generated/GeneratedHasta3lineasTELMEXWidget.dart';
import 'package:flutterapp/telmexapp/generatedmipaqwidget/generated/GeneratedLine17Widget4.dart';
import 'package:flutterapp/telmexapp/generatedmipaqwidget/generated/GeneratedSINCOSTOWidget1.dart';
import 'package:flutterapp/telmexapp/generatedmipaqwidget/generated/GeneratedSINCOSTOWidget.dart';
import 'package:flutterapp/telmexapp/generatedmipaqwidget/generated/GeneratedLine14Widget4.dart';
import 'package:flutterapp/telmexapp/generatedmipaqwidget/generated/GeneratedModeloWidget6.dart';
import 'package:flutterapp/telmexapp/generatedmipaqwidget/generated/GeneratedRectangle16Widget.dart';
import 'package:flutterapp/telmexapp/generatedmipaqwidget/generated/GeneratedLine15Widget4.dart';
import 'package:flutterapp/telmexapp/generatedmipaqwidget/generated/GeneratedMiPaqueteWidget1.dart';
import 'package:flutterapp/telmexapp/generatedmipaqwidget/generated/GeneratedLine13Widget3.dart';
import 'package:flutterapp/telmexapp/generatedmipaqwidget/generated/GeneratedBARRAWidget12.dart';
import 'package:flutterapp/telmexapp/generatedmipaqwidget/generated/Generated300GBWidget.dart';
import 'package:flutterapp/telmexapp/generatedmipaqwidget/generated/GeneratedPaqueteWidget1.dart';
import 'package:flutterapp/telmexapp/generatedmipaqwidget/generated/GeneratedLLAMADASilimitadasWidget.dart';
import 'package:flutterapp/telmexapp/generatedmipaqwidget/generated/GeneratedClarovideo_rn1000x3731Widget.dart';
import 'package:flutterapp/telmexapp/generatedmipaqwidget/generated/Generated\$999Widget1.dart';
import 'package:flutterapp/telmexapp/generatedmipaqwidget/generated/Generated200MbpsWidget.dart';
import 'package:flutterapp/telmexapp/generatedmipaqwidget/generated/GeneratedDrive1Widget.dart';
import 'package:flutterapp/telmexapp/generatedmipaqwidget/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/telmexapp/generatedmipaqwidget/generated/GeneratedAntivirusWidget.dart';

/* Frame MIPAQ
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMIPAQWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 169.0,
                top: 803.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 75.0,
                child: GeneratedBARRAWidget12(),
              ),
              Positioned(
                left: -10.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 451.0,
                height: 212.0,
                child: GeneratedRectangle16Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 420.0,
                height: 91.0,
                child: GeneratedRectangle15Widget(),
              ),
              Positioned(
                left: 6.0,
                top: 23.0,
                right: null,
                bottom: null,
                width: 416.0,
                height: 49.0,
                child: GeneratedMiPaqueteWidget1(),
              ),
              Positioned(
                left: 28.0,
                top: 178.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 36.0,
                child: GeneratedRecargasWidget(),
              ),
              Positioned(
                left: 237.0,
                top: 347.0,
                right: null,
                bottom: null,
                width: 188.0,
                height: 58.0,
                child: GeneratedHasta3lineasTELMEXWidget(),
              ),
              Positioned(
                left: 237.0,
                top: 444.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 30.0,
                child: GeneratedSINCOSTOWidget(),
              ),
              Positioned(
                left: 237.0,
                top: 574.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 30.0,
                child: GeneratedSINCOSTOWidget1(),
              ),
              Positioned(
                left: 167.0,
                top: 178.0,
                right: null,
                bottom: null,
                width: 102.0,
                height: 36.0,
                child: GeneratedPaqueteWidget1(),
              ),
              Positioned(
                left: 35.0,
                top: 574.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 36.0,
                child: GeneratedAntivirusWidget(),
              ),
              Positioned(
                left: 162.0,
                top: 209.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 3.0,
                child: GeneratedLine13Widget3(),
              ),
              Positioned(
                left: 6.0,
                top: 426.0,
                right: null,
                bottom: null,
                width: 403.9989929199219,
                height: 1.0,
                child: GeneratedLine14Widget4(),
              ),
              Positioned(
                left: 6.0,
                top: 485.0,
                right: null,
                bottom: null,
                width: 403.9989929199219,
                height: 1.0,
                child: GeneratedLine15Widget4(),
              ),
              Positioned(
                left: 11.0,
                top: 557.0,
                right: null,
                bottom: null,
                width: 403.9989929199219,
                height: 1.0,
                child: GeneratedLine16Widget3(),
              ),
              Positioned(
                left: 6.000097751617432,
                top: 632.5,
                right: null,
                bottom: null,
                width: 403.9989929199219,
                height: 5.684341886080802e-14,
                child: GeneratedLine17Widget4(),
              ),
              Positioned(
                left: 237.0,
                top: 508.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 30.0,
                child: Generated300GBWidget(),
              ),
              Positioned(
                left: 366.0,
                top: 584.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedModeloWidget6(),
              ),
              Positioned(
                left: -2.0,
                top: 347.0,
                right: null,
                bottom: null,
                width: 203.0,
                height: 70.0,
                child: GeneratedLLAMADASilimitadasWidget(),
              ),
              Positioned(
                left: 302.0,
                top: 178.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 36.0,
                child: GeneratedHistorialWidget(),
              ),
              Positioned(
                left: 88.0,
                top: 267.0,
                right: null,
                bottom: null,
                width: 239.0,
                height: 64.0,
                child: Generated200MbpsWidget(),
              ),
              Positioned(
                left: 27.0,
                top: 444.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 29.0,
                child: GeneratedClarovideo_rn1000x3731Widget(),
              ),
              Positioned(
                left: -10.0,
                top: 510.0,
                right: null,
                bottom: null,
                width: 204.0,
                height: 28.0,
                child: GeneratedDrive1Widget(),
              ),
              Positioned(
                left: 114.0,
                top: 671.0,
                right: null,
                bottom: null,
                width: 185.0,
                height: 99.0,
                child: Generated$999Widget1(),
              )
            ]),
      ),
    ));
  }
}
