import 'package:flutter/material.dart';
import 'package:flutterapp/telmexapp/generatedmaswidget11/generated/GeneratedBARRAWidget11.dart';
import 'package:flutterapp/telmexapp/generatedmaswidget11/generated/GeneratedUnnamed1Widget.dart';

/* Frame MAS
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMASWidget11 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 169.0,
                top: 806.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 75.0,
                child: GeneratedBARRAWidget11(),
              ),
              Positioned(
                left: -12.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 426.0,
                height: 806.0,
                child: GeneratedUnnamed1Widget(),
              )
            ]),
      ),
    ));
  }
}
