import 'package:flutter/material.dart';
import 'package:flutterapp/telmexapp/generatedwifiwidget/generated/GeneratedKeysharpWidget.dart';
import 'package:flutterapp/telmexapp/generatedwifiwidget/generated/GeneratedBARRAWidget1.dart';
import 'package:flutterapp/telmexapp/generatedwifiwidget/generated/GeneratedQrcodesharpWidget.dart';
import 'package:flutterapp/telmexapp/generatedwifiwidget/generated/GeneratedCompartirmiRedWidget.dart';
import 'package:flutterapp/telmexapp/generatedwifiwidget/generated/GeneratedPeoplesharpWidget.dart';
import 'package:flutterapp/telmexapp/generatedwifiwidget/generated/GeneratedAsistenciaWidget1.dart';
import 'package:flutterapp/telmexapp/generatedwifiwidget/generated/GeneratedAyudaconlaredWidget.dart';
import 'package:flutterapp/telmexapp/generatedwifiwidget/generated/GeneratedWifiWidget2.dart';
import 'package:flutterapp/telmexapp/generatedwifiwidget/generated/GeneratedLine14Widget.dart';
import 'package:flutterapp/telmexapp/generatedwifiwidget/generated/GeneratedVectorWidget34.dart';
import 'package:flutterapp/telmexapp/generatedwifiwidget/generated/GeneratedContraseaWidget.dart';
import 'package:flutterapp/telmexapp/generatedwifiwidget/generated/GeneratedMiredWidget1.dart';
import 'package:flutterapp/telmexapp/generatedwifiwidget/generated/GeneratedLogorssWidget.dart';
import 'package:flutterapp/telmexapp/generatedwifiwidget/generated/GeneratedModeloWidget.dart';
import 'package:flutterapp/telmexapp/generatedwifiwidget/generated/GeneratedAyudaconmiRedWidget.dart';
import 'package:flutterapp/telmexapp/generatedwifiwidget/generated/GeneratedLine13Widget.dart';
import 'package:flutterapp/telmexapp/generatedwifiwidget/generated/GeneratedMiredWidget.dart';
import 'package:flutterapp/telmexapp/generatedwifiwidget/generated/Generated15642Widget.dart';
import 'package:flutterapp/telmexapp/generatedwifiwidget/generated/GeneratedContraseaWidget1.dart';
import 'package:flutterapp/telmexapp/generatedwifiwidget/generated/GeneratedLine15Widget.dart';
import 'package:flutterapp/telmexapp/generatedwifiwidget/generated/GeneratedLine16Widget.dart';
import 'package:flutterapp/telmexapp/generatedwifiwidget/generated/GeneratedWidget.dart';
import 'package:flutterapp/telmexapp/generatedwifiwidget/generated/GeneratedApagarredWidget.dart';
import 'package:flutterapp/telmexapp/generatedwifiwidget/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/telmexapp/generatedwifiwidget/generated/GeneratedCompartirredWidget.dart';
import 'package:flutterapp/telmexapp/generatedwifiwidget/generated/GeneratedModeloWidget1.dart';
import 'package:flutterapp/telmexapp/generatedwifiwidget/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/telmexapp/generatedwifiwidget/generated/GeneratedConstructsharpWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/telmexapp/generatedwifiwidget/generated/GeneratedEllipse2Widget.dart';
import 'package:flutterapp/telmexapp/generatedwifiwidget/generated/GeneratedAsistenciaWidget2.dart';
import 'package:flutterapp/telmexapp/generatedwifiwidget/generated/GeneratedEaselWidget.dart';
import 'package:flutterapp/telmexapp/generatedwifiwidget/generated/GeneratedMICHISWidget.dart';
import 'package:flutterapp/telmexapp/generatedwifiwidget/generated/GeneratedLine17Widget.dart';
import 'package:flutterapp/telmexapp/generatedwifiwidget/generated/GeneratedLine18Widget.dart';
import 'package:flutterapp/telmexapp/generatedwifiwidget/generated/GeneratedGestiondeWiFiWidget.dart';
import 'package:flutterapp/telmexapp/generatedwifiwidget/generated/GeneratedHomesharpWidget.dart';

/* Frame WIFI
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWIFIWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 245, 245),
                ),
              ),
              Positioned(
                left: 169.0,
                top: 803.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 75.0,
                child: GeneratedBARRAWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 435.0,
                height: 203.0,
                child: GeneratedRectangle8Widget(),
              ),
              Positioned(
                left: -15.0,
                top: -19.0,
                right: null,
                bottom: null,
                width: 456.0,
                height: 101.0,
                child: GeneratedRectangle9Widget(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 214.0,
                height: 197.0,
                child: TransformHelper.translate(
                    x: -10.00,
                    y: -255.50,
                    z: 0,
                    child: GeneratedEllipse2Widget()),
              ),
              Positioned(
                left: 108.0,
                top: 110.0,
                right: null,
                bottom: null,
                width: 177.0,
                height: 180.0,
                child: GeneratedWifiWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 31.0,
                right: null,
                bottom: null,
                width: 416.0,
                height: 49.0,
                child: GeneratedGestiondeWiFiWidget(),
              ),
              Positioned(
                left: 26.0,
                top: 307.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedQrcodesharpWidget(),
              ),
              Positioned(
                left: 87.0,
                top: 307.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 30.0,
                child: GeneratedCompartirmiRedWidget(),
              ),
              Positioned(
                left: 90.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 30.0,
                child: GeneratedMiredWidget(),
              ),
              Positioned(
                left: 90.0,
                top: 426.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 33.0,
                child: GeneratedContraseaWidget(),
              ),
              Positioned(
                left: 90.0,
                top: 516.0,
                right: null,
                bottom: null,
                width: 119.0,
                height: 30.0,
                child: GeneratedApagarredWidget(),
              ),
              Positioned(
                left: 90.0,
                top: 652.0,
                right: null,
                bottom: null,
                width: 194.0,
                height: 30.0,
                child: GeneratedAyudaconmiRedWidget(),
              ),
              Positioned(
                left: 90.0,
                top: 729.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 33.0,
                child: GeneratedAsistenciaWidget1(),
              ),
              Positioned(
                left: 6.0,
                top: 357.0,
                right: null,
                bottom: null,
                width: 403.9989929199219,
                height: 1.0,
                child: GeneratedLine13Widget(),
              ),
              Positioned(
                left: 6.0,
                top: 426.0,
                right: null,
                bottom: null,
                width: 403.9989929199219,
                height: 1.0,
                child: GeneratedLine14Widget(),
              ),
              Positioned(
                left: 6.0,
                top: 495.0,
                right: null,
                bottom: null,
                width: 403.9989929199219,
                height: 1.0,
                child: GeneratedLine15Widget(),
              ),
              Positioned(
                left: 6.0,
                top: 564.0,
                right: null,
                bottom: null,
                width: 403.9989929199219,
                height: 1.0,
                child: GeneratedLine16Widget(),
              ),
              Positioned(
                left: 6.0,
                top: 633.0,
                right: null,
                bottom: null,
                width: 403.9989929199219,
                height: 1.0,
                child: GeneratedLine17Widget(),
              ),
              Positioned(
                left: 6.0,
                top: 702.0,
                right: null,
                bottom: null,
                width: 403.9989929199219,
                height: 1.0,
                child: GeneratedLine18Widget(),
              ),
              Positioned(
                left: 90.0,
                top: 567.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 30.0,
                child: GeneratedModeloWidget(),
              ),
              Positioned(
                left: 26.0,
                top: 376.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedHomesharpWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 728.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedPeoplesharpWidget(),
              ),
              Positioned(
                left: 28.0,
                top: 448.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedKeysharpWidget(),
              ),
              Positioned(
                left: 28.0,
                top: 652.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedConstructsharpWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 584.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedEaselWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.10869565217391304;
                  double scaleX = (constraints.maxWidth * percentWidth) / 45.0;

                  double percentHeight = 0.027901785714285716;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 25.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8671497584541062,
                        translateY: constraints.maxHeight * 0.5792410714285714,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget34())
                  ]);
                }),
              ),
              Positioned(
                left: 364.0,
                top: 383.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedMiredWidget1(),
              ),
              Positioned(
                left: 364.0,
                top: 452.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedContraseaWidget1(),
              ),
              Positioned(
                left: 28.0,
                top: 514.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedLogorssWidget(),
              ),
              Positioned(
                left: 366.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedCompartirredWidget(),
              ),
              Positioned(
                left: 366.0,
                top: 584.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedModeloWidget1(),
              ),
              Positioned(
                left: 366.0,
                top: 655.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedAyudaconlaredWidget(),
              ),
              Positioned(
                left: 366.0,
                top: 731.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedAsistenciaWidget2(),
              ),
              Positioned(
                left: 32.0,
                top: 386.0,
                right: null,
                bottom: null,
                width: 203.0,
                height: 34.0,
                child: GeneratedMICHISWidget(),
              ),
              Positioned(
                left: 85.0,
                top: 421.0,
                right: null,
                bottom: null,
                width: 157.0,
                height: 80.0,
                child: GeneratedWidget(),
              ),
              Positioned(
                left: 87.0,
                top: 598.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 33.0,
                child: Generated15642Widget(),
              )
            ]),
      ),
    ));
  }
}
