import 'package:flutter/material.dart';
import 'package:flutterapp/telmexapp/generatedestadodecuetawidget/generated/GeneratedRecibotelmex1Widget.dart';
import 'package:flutterapp/telmexapp/generatedestadodecuetawidget/generated/GeneratedBARRAWidget7.dart';

/* Frame Estadode cueta
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEstadodecuetaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 245, 245),
                ),
              ),
              Positioned(
                left: 169.0,
                top: 791.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 75.0,
                child: GeneratedBARRAWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: 1.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 779.0,
                child: GeneratedRecibotelmex1Widget(),
              )
            ]),
      ),
    ));
  }
}
