import 'package:flutter/material.dart';
import 'package:flutterapp/telmexapp/generatedwifiapagarwidget/generated/GeneratedAyudaconmiRedWidget3.dart';
import 'package:flutterapp/telmexapp/generatedwifiapagarwidget/generated/GeneratedWifiWidget6.dart';
import 'package:flutterapp/telmexapp/generatedwifiapagarwidget/generated/GeneratedModeloWidget4.dart';
import 'package:flutterapp/telmexapp/generatedwifiapagarwidget/generated/GeneratedCompartirredWidget3.dart';
import 'package:flutterapp/telmexapp/generatedwifiapagarwidget/generated/GeneratedEaselWidget2.dart';
import 'package:flutterapp/telmexapp/generatedwifiapagarwidget/generated/GeneratedAyudaconlaredWidget2.dart';
import 'package:flutterapp/telmexapp/generatedwifiapagarwidget/generated/GeneratedMICHISWidget3.dart';
import 'package:flutterapp/telmexapp/generatedwifiapagarwidget/generated/GeneratedKeysharpWidget3.dart';
import 'package:flutterapp/telmexapp/generatedwifiapagarwidget/generated/GeneratedApagarredWidget2.dart';
import 'package:flutterapp/telmexapp/generatedwifiapagarwidget/generated/Generated15642Widget2.dart';
import 'package:flutterapp/telmexapp/generatedwifiapagarwidget/generated/GeneratedLine17Widget3.dart';
import 'package:flutterapp/telmexapp/generatedwifiapagarwidget/generated/GeneratedModeloWidget5.dart';
import 'package:flutterapp/telmexapp/generatedwifiapagarwidget/generated/GeneratedPeoplesharpWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/telmexapp/generatedwifiapagarwidget/generated/GeneratedVectorWidget118.dart';
import 'package:flutterapp/telmexapp/generatedwifiapagarwidget/generated/GeneratedHomesharpWidget3.dart';
import 'package:flutterapp/telmexapp/generatedwifiapagarwidget/generated/GeneratedLine18Widget3.dart';
import 'package:flutterapp/telmexapp/generatedwifiapagarwidget/generated/GeneratedLine15Widget3.dart';
import 'package:flutterapp/telmexapp/generatedwifiapagarwidget/generated/GeneratedCompartirmiRedWidget3.dart';
import 'package:flutterapp/telmexapp/generatedwifiapagarwidget/generated/GeneratedAsistenciaWidget6.dart';
import 'package:flutterapp/telmexapp/generatedwifiapagarwidget/generated/GeneratedEllipse2Widget2.dart';
import 'package:flutterapp/telmexapp/generatedwifiapagarwidget/generated/GeneratedGestiondeWiFiWidget2.dart';
import 'package:flutterapp/telmexapp/generatedwifiapagarwidget/generated/GeneratedLine16Widget2.dart';
import 'package:flutterapp/telmexapp/generatedwifiapagarwidget/generated/GeneratedBARRAWidget3.dart';
import 'package:flutterapp/telmexapp/generatedwifiapagarwidget/generated/GeneratedQrcodesharpWidget3.dart';
import 'package:flutterapp/telmexapp/generatedwifiapagarwidget/generated/GeneratedMiredWidget6.dart';
import 'package:flutterapp/telmexapp/generatedwifiapagarwidget/generated/GeneratedMiredWidget7.dart';
import 'package:flutterapp/telmexapp/generatedwifiapagarwidget/generated/GeneratedLine13Widget2.dart';
import 'package:flutterapp/telmexapp/generatedwifiapagarwidget/generated/GeneratedContraseaWidget6.dart';
import 'package:flutterapp/telmexapp/generatedwifiapagarwidget/generated/GeneratedLine14Widget3.dart';
import 'package:flutterapp/telmexapp/generatedwifiapagarwidget/generated/GeneratedAsistenciaWidget7.dart';
import 'package:flutterapp/telmexapp/generatedwifiapagarwidget/generated/GeneratedWidget3.dart';
import 'package:flutterapp/telmexapp/generatedwifiapagarwidget/generated/GeneratedRectangle8Widget2.dart';
import 'package:flutterapp/telmexapp/generatedwifiapagarwidget/generated/GeneratedContraseaWidget7.dart';
import 'package:flutterapp/telmexapp/generatedwifiapagarwidget/generated/GeneratedLogorssWidget2.dart';
import 'package:flutterapp/telmexapp/generatedwifiapagarwidget/generated/GeneratedConstructsharpWidget3.dart';
import 'package:flutterapp/telmexapp/generatedwifiapagarwidget/generated/GeneratedRectangle9Widget3.dart';

/* Frame WIFIapagar
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWIFIapagarWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 245, 245),
                ),
              ),
              Positioned(
                left: 169.0,
                top: 803.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 75.0,
                child: GeneratedBARRAWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 435.0,
                height: 203.0,
                child: GeneratedRectangle8Widget2(),
              ),
              Positioned(
                left: -15.0,
                top: -19.0,
                right: null,
                bottom: null,
                width: 456.0,
                height: 101.0,
                child: GeneratedRectangle9Widget3(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 214.0,
                height: 197.0,
                child: TransformHelper.translate(
                    x: -10.00,
                    y: -255.50,
                    z: 0,
                    child: GeneratedEllipse2Widget2()),
              ),
              Positioned(
                left: 108.0,
                top: 110.0,
                right: null,
                bottom: null,
                width: 177.0,
                height: 180.0,
                child: GeneratedWifiWidget6(),
              ),
              Positioned(
                left: 0.0,
                top: 31.0,
                right: null,
                bottom: null,
                width: 416.0,
                height: 49.0,
                child: GeneratedGestiondeWiFiWidget2(),
              ),
              Positioned(
                left: 26.0,
                top: 307.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedQrcodesharpWidget3(),
              ),
              Positioned(
                left: 87.0,
                top: 307.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 30.0,
                child: GeneratedCompartirmiRedWidget3(),
              ),
              Positioned(
                left: 90.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 30.0,
                child: GeneratedMiredWidget6(),
              ),
              Positioned(
                left: 90.0,
                top: 426.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 33.0,
                child: GeneratedContraseaWidget6(),
              ),
              Positioned(
                left: 90.0,
                top: 516.0,
                right: null,
                bottom: null,
                width: 119.0,
                height: 30.0,
                child: GeneratedApagarredWidget2(),
              ),
              Positioned(
                left: 90.0,
                top: 652.0,
                right: null,
                bottom: null,
                width: 194.0,
                height: 30.0,
                child: GeneratedAyudaconmiRedWidget3(),
              ),
              Positioned(
                left: 90.0,
                top: 729.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 33.0,
                child: GeneratedAsistenciaWidget6(),
              ),
              Positioned(
                left: 6.0,
                top: 357.0,
                right: null,
                bottom: null,
                width: 403.9989929199219,
                height: 1.0,
                child: GeneratedLine13Widget2(),
              ),
              Positioned(
                left: 6.0,
                top: 426.0,
                right: null,
                bottom: null,
                width: 403.9989929199219,
                height: 1.0,
                child: GeneratedLine14Widget3(),
              ),
              Positioned(
                left: 6.0,
                top: 495.0,
                right: null,
                bottom: null,
                width: 403.9989929199219,
                height: 1.0,
                child: GeneratedLine15Widget3(),
              ),
              Positioned(
                left: 6.0,
                top: 564.0,
                right: null,
                bottom: null,
                width: 403.9989929199219,
                height: 1.0,
                child: GeneratedLine16Widget2(),
              ),
              Positioned(
                left: 6.0,
                top: 633.0,
                right: null,
                bottom: null,
                width: 403.9989929199219,
                height: 1.0,
                child: GeneratedLine17Widget3(),
              ),
              Positioned(
                left: 6.0,
                top: 702.0,
                right: null,
                bottom: null,
                width: 403.9989929199219,
                height: 1.0,
                child: GeneratedLine18Widget3(),
              ),
              Positioned(
                left: 90.0,
                top: 567.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 30.0,
                child: GeneratedModeloWidget4(),
              ),
              Positioned(
                left: 26.0,
                top: 376.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedHomesharpWidget3(),
              ),
              Positioned(
                left: 24.0,
                top: 728.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedPeoplesharpWidget2(),
              ),
              Positioned(
                left: 28.0,
                top: 448.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedKeysharpWidget3(),
              ),
              Positioned(
                left: 28.0,
                top: 652.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedConstructsharpWidget3(),
              ),
              Positioned(
                left: 24.0,
                top: 584.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedEaselWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.10869565217391304;
                  double scaleX = (constraints.maxWidth * percentWidth) / 45.0;

                  double percentHeight = 0.027901785714285716;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 25.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.9637681159420289,
                        translateY: constraints.maxHeight * 0.5792410714285714,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget118())
                  ]);
                }),
              ),
              Positioned(
                left: 364.0,
                top: 383.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedMiredWidget7(),
              ),
              Positioned(
                left: 364.0,
                top: 452.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedContraseaWidget7(),
              ),
              Positioned(
                left: 28.0,
                top: 514.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedLogorssWidget2(),
              ),
              Positioned(
                left: 366.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedCompartirredWidget3(),
              ),
              Positioned(
                left: 366.0,
                top: 584.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedModeloWidget5(),
              ),
              Positioned(
                left: 366.0,
                top: 655.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedAyudaconlaredWidget2(),
              ),
              Positioned(
                left: 366.0,
                top: 731.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedAsistenciaWidget7(),
              ),
              Positioned(
                left: 32.0,
                top: 386.0,
                right: null,
                bottom: null,
                width: 203.0,
                height: 34.0,
                child: GeneratedMICHISWidget3(),
              ),
              Positioned(
                left: 85.0,
                top: 421.0,
                right: null,
                bottom: null,
                width: 157.0,
                height: 80.0,
                child: GeneratedWidget3(),
              ),
              Positioned(
                left: 87.0,
                top: 598.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 33.0,
                child: Generated15642Widget2(),
              )
            ]),
      ),
    ));
  }
}
