import 'package:flutter/material.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/GeneratedMiTelefonoWidget.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/GeneratedWiFiWidget1.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/GeneratedDocumentattachsharpWidget.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/GeneratedVectorWidget182.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/GeneratedLine9Widget.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/GeneratedLine10Widget.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/GeneratedPeoplesharpWidget4.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/GeneratedAsistenteWidget.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/GeneratedNoCuentaTelfonoWidget.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/GeneratedEstadodeCuentaWidget.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/GeneratedSuperMarioWidget.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/GeneratedComprasenlineaWidget1.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/GeneratedLine3Widget.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/GeneratedLine1Widget.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/GeneratedLine2Widget.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/GeneratedFormasdepagoWidget1.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/GeneratedFormasdePagoWidget1.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/GeneratedMitelefonoWidget.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/GeneratedWifiWidget13.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/GeneratedWifiWidget14.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/GeneratedLine7Widget.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/GeneratedNotificacionesWidget.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/GeneratedLine4Widget.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/GeneratedPerfilWidget20.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/GeneratedVectorWidget180.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/GeneratedMiPaqueteWidget.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/GeneratedEllipse1Widget.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/Generated41325495Widget.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/GeneratedPaqueteWidget.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/GeneratedNotificationsWidget.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/GeneratedBrisaContrerasWidget.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/GeneratedVectorWidget181.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/GeneratedCashsharpWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/GeneratedLine6Widget.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/GeneratedBARRAWidget9.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/GeneratedAsistenciaWidget8.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/GeneratedMiCuentaWidget.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/GeneratedEstadodecuentaWidget.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/Generated154679616Widget.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/GeneratedLine8Widget.dart';
import 'package:flutterapp/telmexapp/generatedperfilwidget/generated/GeneratedComprasenlineaWidget.dart';

/* Frame PERFIL
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPERFILWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 245, 245),
                ),
              ),
              Positioned(
                left: 169.0,
                top: 797.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 75.0,
                child: GeneratedBARRAWidget9(),
              ),
              Positioned(
                left: 12.0,
                top: 26.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 59.0,
                child: GeneratedPerfilWidget20(),
              ),
              Positioned(
                left: 12.0,
                top: 101.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 108.0,
                child: GeneratedEllipse1Widget(),
              ),
              Positioned(
                left: 13.0,
                top: 106.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 99.0,
                child: GeneratedSuperMarioWidget(),
              ),
              Positioned(
                left: 145.0,
                top: 104.0,
                right: null,
                bottom: null,
                width: 225.0,
                height: 34.0,
                child: GeneratedBrisaContrerasWidget(),
              ),
              Positioned(
                left: 145.0,
                top: 147.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 67.0,
                child: GeneratedNoCuentaTelfonoWidget(),
              ),
              Positioned(
                left: 278.0,
                top: 152.0,
                right: null,
                bottom: null,
                width: 126.0,
                height: 21.0,
                child: Generated154679616Widget(),
              ),
              Positioned(
                left: 278.0,
                top: 181.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 28.0,
                child: Generated41325495Widget(),
              ),
              Positioned(
                left: 7.0,
                top: 229.0,
                right: null,
                bottom: null,
                width: 399.0,
                height: 1.0,
                child: GeneratedLine1Widget(),
              ),
              Positioned(
                left: 7.0,
                top: 277.0,
                right: null,
                bottom: null,
                width: 399.0,
                height: 1.0,
                child: GeneratedLine2Widget(),
              ),
              Positioned(
                left: 7.0,
                top: 520.0,
                right: null,
                bottom: null,
                width: 399.0,
                height: 1.0,
                child: GeneratedLine3Widget(),
              ),
              Positioned(
                left: 7.0,
                top: 456.0,
                right: null,
                bottom: null,
                width: 399.0,
                height: 1.0,
                child: GeneratedLine4Widget(),
              ),
              Positioned(
                left: 7.0,
                top: 392.0,
                right: null,
                bottom: null,
                width: 399.0,
                height: 1.0,
                child: GeneratedLine8Widget(),
              ),
              Positioned(
                left: 7.0,
                top: 584.0,
                right: null,
                bottom: null,
                width: 399.0,
                height: 1.0,
                child: GeneratedLine6Widget(),
              ),
              Positioned(
                left: 7.0,
                top: 648.0,
                right: null,
                bottom: null,
                width: 399.0,
                height: 1.0,
                child: GeneratedLine7Widget(),
              ),
              Positioned(
                left: 7.0,
                top: 712.0,
                right: null,
                bottom: null,
                width: 399.0,
                height: 1.0,
                child: GeneratedLine9Widget(),
              ),
              Positioned(
                left: 7.0,
                top: 776.0,
                right: null,
                bottom: null,
                width: 399.0,
                height: 1.0,
                child: GeneratedLine10Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 237.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedNotificationsWidget(),
              ),
              Positioned(
                left: 56.0,
                top: 239.0,
                right: null,
                bottom: null,
                width: 164.0,
                height: 36.0,
                child: GeneratedNotificacionesWidget(),
              ),
              Positioned(
                left: 13.0,
                top: 288.0,
                right: null,
                bottom: null,
                width: 151.0,
                height: 41.0,
                child: GeneratedMiCuentaWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 412.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedCashsharpWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 355.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedDocumentattachsharpWidget(),
              ),
              Positioned(
                left: 59.0,
                top: 354.0,
                right: null,
                bottom: null,
                width: 204.0,
                height: 34.0,
                child: GeneratedEstadodeCuentaWidget(),
              ),
              Positioned(
                left: 59.0,
                top: 728.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 33.0,
                child: GeneratedAsistenteWidget(),
              ),
              Positioned(
                left: 59.0,
                top: 666.0,
                right: null,
                bottom: null,
                width: 196.0,
                height: 33.0,
                child: GeneratedComprasenlineaWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.07246376811594203;
                  double scaleX = (constraints.maxWidth * percentWidth) / 30.0;

                  double percentHeight = 0.033482142857142856;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 30.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.04106280193236715,
                        translateY: constraints.maxHeight * 0.7455357142857143,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget180())
                  ]);
                }),
              ),
              Positioned(
                left: 59.0,
                top: 412.0,
                right: null,
                bottom: null,
                width: 177.0,
                height: 30.0,
                child: GeneratedFormasdePagoWidget1(),
              ),
              Positioned(
                left: 59.0,
                top: 478.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 33.0,
                child: GeneratedWiFiWidget1(),
              ),
              Positioned(
                left: 59.0,
                top: 538.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 30.0,
                child: GeneratedMiPaqueteWidget(),
              ),
              Positioned(
                left: 59.0,
                top: 601.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 30.0,
                child: GeneratedMiTelefonoWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06521739130434782;
                  double scaleX = (constraints.maxWidth * percentWidth) / 27.0;

                  double percentHeight = 0.033482142857142856;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 30.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.03864734299516908,
                        translateY: constraints.maxHeight * 0.6662946428571429,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget181())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.07246376811594203;
                  double scaleX = (constraints.maxWidth * percentWidth) / 30.0;

                  double percentHeight = 0.033482142857142856;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 30.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.04106280193236715,
                        translateY: constraints.maxHeight * 0.5993303571428571,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget182())
                  ]);
                }),
              ),
              Positioned(
                left: 18.0,
                top: 474.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedWifiWidget13(),
              ),
              Positioned(
                left: 18.0,
                top: 728.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedPeoplesharpWidget4(),
              ),
              Positioned(
                left: 376.0,
                top: 354.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedEstadodecuentaWidget(),
              ),
              Positioned(
                left: 376.0,
                top: 419.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedFormasdepagoWidget1(),
              ),
              Positioned(
                left: 376.0,
                top: 479.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedWifiWidget14(),
              ),
              Positioned(
                left: 376.0,
                top: 537.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedPaqueteWidget(),
              ),
              Positioned(
                left: 376.0,
                top: 600.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedMitelefonoWidget(),
              ),
              Positioned(
                left: 376.0,
                top: 663.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedComprasenlineaWidget1(),
              ),
              Positioned(
                left: 376.0,
                top: 726.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedAsistenciaWidget8(),
              )
            ]),
      ),
    ));
  }
}
