import 'package:flutter/material.dart';
import 'package:flutterapp/telmexapp/generatedwifimodelowidget/generated/GeneratedBARRAWidget2.dart';
import 'package:flutterapp/telmexapp/generatedwifimodelowidget/generated/GeneratedQrcodesharpWidget1.dart';
import 'package:flutterapp/telmexapp/generatedwifimodelowidget/generated/GeneratedDescarga1Widget.dart';
import 'package:flutterapp/telmexapp/generatedwifimodelowidget/generated/GeneratedWidget1.dart';
import 'package:flutterapp/telmexapp/generatedwifimodelowidget/generated/GeneratedMiredWidget2.dart';
import 'package:flutterapp/telmexapp/generatedwifimodelowidget/generated/GeneratedCompartirredWidget1.dart';
import 'package:flutterapp/telmexapp/generatedwifimodelowidget/generated/GeneratedContraseaWidget2.dart';
import 'package:flutterapp/telmexapp/generatedwifimodelowidget/generated/GeneratedContraseaWidget3.dart';
import 'package:flutterapp/telmexapp/generatedwifimodelowidget/generated/GeneratedKeysharpWidget1.dart';
import 'package:flutterapp/telmexapp/generatedwifimodelowidget/generated/GeneratedMICHISWidget1.dart';
import 'package:flutterapp/telmexapp/generatedwifimodelowidget/generated/GeneratedLine17Widget1.dart';
import 'package:flutterapp/telmexapp/generatedwifimodelowidget/generated/GeneratedHomesharpWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/telmexapp/generatedwifimodelowidget/generated/GeneratedAyudaconmiRedWidget1.dart';
import 'package:flutterapp/telmexapp/generatedwifimodelowidget/generated/GeneratedRectangle9Widget1.dart';
import 'package:flutterapp/telmexapp/generatedwifimodelowidget/generated/GeneratedLine14Widget1.dart';
import 'package:flutterapp/telmexapp/generatedwifimodelowidget/generated/GeneratedCompartirmiRedWidget1.dart';
import 'package:flutterapp/telmexapp/generatedwifimodelowidget/generated/GeneratedVectorWidget63.dart';
import 'package:flutterapp/telmexapp/generatedwifimodelowidget/generated/GeneratedConstructsharpWidget1.dart';
import 'package:flutterapp/telmexapp/generatedwifimodelowidget/generated/GeneratedAsistenciaWidget3.dart';
import 'package:flutterapp/telmexapp/generatedwifimodelowidget/generated/GeneratedMiredWidget3.dart';
import 'package:flutterapp/telmexapp/generatedwifimodelowidget/generated/GeneratedLine18Widget1.dart';
import 'package:flutterapp/telmexapp/generatedwifimodelowidget/generated/GeneratedLine15Widget1.dart';
import 'package:flutterapp/telmexapp/generatedwifimodelowidget/generated/GeneratedModelo15642Widget.dart';

/* Frame WIFIMODELO
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWIFIMODELOWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 245, 245),
                ),
              ),
              Positioned(
                left: 169.0,
                top: 803.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 75.0,
                child: GeneratedBARRAWidget2(),
              ),
              Positioned(
                left: -15.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 457.0,
                height: 146.0,
                child: GeneratedRectangle9Widget1(),
              ),
              Positioned(
                left: 39.0,
                top: 98.0,
                right: null,
                bottom: null,
                width: 416.0,
                height: 49.0,
                child: GeneratedModelo15642Widget(),
              ),
              Positioned(
                left: 26.0,
                top: 514.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedQrcodesharpWidget1(),
              ),
              Positioned(
                left: 87.0,
                top: 517.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 30.0,
                child: GeneratedCompartirmiRedWidget1(),
              ),
              Positioned(
                left: 90.0,
                top: 566.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 30.0,
                child: GeneratedMiredWidget2(),
              ),
              Positioned(
                left: 90.0,
                top: 631.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 33.0,
                child: GeneratedContraseaWidget2(),
              ),
              Positioned(
                left: 90.0,
                top: 732.0,
                right: null,
                bottom: null,
                width: 194.0,
                height: 30.0,
                child: GeneratedAyudaconmiRedWidget1(),
              ),
              Positioned(
                left: 6.0,
                top: 499.0,
                right: null,
                bottom: null,
                width: 403.9989929199219,
                height: 1.0,
                child: GeneratedLine14Widget1(),
              ),
              Positioned(
                left: 6.0,
                top: 567.0,
                right: null,
                bottom: null,
                width: 403.9989929199219,
                height: 1.0,
                child: GeneratedLine15Widget1(),
              ),
              Positioned(
                left: 6.0,
                top: 633.0,
                right: null,
                bottom: null,
                width: 403.9989929199219,
                height: 1.0,
                child: GeneratedLine17Widget1(),
              ),
              Positioned(
                left: 6.0,
                top: 702.0,
                right: null,
                bottom: null,
                width: 403.9989929199219,
                height: 1.0,
                child: GeneratedLine18Widget1(),
              ),
              Positioned(
                left: 26.0,
                top: 580.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedHomesharpWidget1(),
              ),
              Positioned(
                left: 28.0,
                top: 646.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedKeysharpWidget1(),
              ),
              Positioned(
                left: 28.0,
                top: 726.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedConstructsharpWidget1(),
              ),
              Positioned(
                left: 364.0,
                top: 585.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedMiredWidget3(),
              ),
              Positioned(
                left: 364.0,
                top: 656.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedContraseaWidget3(),
              ),
              Positioned(
                left: 366.0,
                top: 516.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedCompartirredWidget1(),
              ),
              Positioned(
                left: 366.0,
                top: 731.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedAsistenciaWidget3(),
              ),
              Positioned(
                left: 32.0,
                top: 588.0,
                right: null,
                bottom: null,
                width: 203.0,
                height: 34.0,
                child: GeneratedMICHISWidget1(),
              ),
              Positioned(
                left: 85.0,
                top: 623.0,
                right: null,
                bottom: null,
                width: 157.0,
                height: 80.0,
                child: GeneratedWidget1(),
              ),
              Positioned(
                left: 6.0,
                top: 145.0,
                right: null,
                bottom: null,
                width: 386.0,
                height: 288.0,
                child: GeneratedDescarga1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06551932367149758;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 27.125;

                  double percentHeight = 0.041015625;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 36.75;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.00966183574879227,
                        translateY: constraints.maxHeight * 0.11272321428571429,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget63())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
